version: '3.8'

services:
  byf-app:
    build: 
      context: ../../.. 
      dockerfile: src/config/docker/Dockerfile
    ports:
      - '${APP_PORT}:3000'
    depends_on:
      - byf-db

  byf-db: # If this name is changed, DATABASE_HOST in .env file must be changed too
    image: 'postgres:13'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      TZ: Europe/Paris
    volumes:
      - 'byf-db-data:/var/lib/postgresql/data'

volumes:
  byf-db-data: