name: Deploy to Dev

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: [self-hosted, linux, x64, dev, back]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and deploy
      env:
        DOCKER_COMPOSE_FILE: back/src/config/docker/docker-compose.yml
      run: |
        docker-compose -f $DOCKER_COMPOSE_FILE build
        docker-compose -f $DOCKER_COMPOSE_FILE down
        docker-compose -f $DOCKER_COMPOSE_FILE up -d